import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthContext } from "@/contexts/authContext/AuthContext";
import ProjectContext from "@/contexts/projectContext/ProjectContext";
import UserContext from "@/contexts/userContext";
import TaskContext from "@/contexts/taskContext/TaskContext";
import MemberContext from "@/contexts/memberContext/MemberContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <AuthContext>
          <ProjectContext>
            <UserContext>
              <TaskContext>
                <MemberContext>
                  <div>
                    {children}
                  </div>
                </MemberContext>
              </TaskContext>
            </UserContext>
          </ProjectContext>
        </AuthContext>
      </body>
    </html>
  );
}
